[plugin-info]
SHORT_PLUGIN_NAME = 'zaber'

package-url = 'https://github.com/Attolab/pymodaq_plugins_zaber' #to modify
description = 'Plugin for Zaber actuators'

author = 'Romain Geneaux'
author-email = 'romain.geneaux@cea.fr'
license = 'MIT'

[plugin-install]
#packages required for your plugin:
packages-required = []
